spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: algorithm-service
              uri: lb://ALGORITHM-SERVICE
              predicates:
                - Path=/api/algo/**
              filters:
                - name: AuthComponent
                - StripPrefix=2

            - id: warehouse-service
              uri: lb://WAREHOUSE-SERVICE
              predicates:
                - Path=/api/warehouse/**
              filters:
                - name: AuthComponent
                - StripPrefix=2

            - id: transport-management-service
              uri: lb://TRANSPORT-MANAGEMENT-SERVICE
              predicates:
                - Path=/api/transport/**
              filters:
                - name: AuthComponent
                - StripPrefix=2

            - id: item-management-service
              uri: lb://ITEM-MANAGEMENT-SERVICE
              predicates:
                - Path=/api/items/**
              filters:
                - name: AuthComponent
                - StripPrefix=2

            - id: delivery-service
              uri: lb://DELIVERY-SERVICE
              predicates:
                - Path=/api/delivery/**
              filters:
                - name: AuthComponent
                - StripPrefix=2